### ISSUE TITLE
Pause/Unpause all alerts in one shot does not work

### ISSUE THREAD

**Issue by liptanbiswas** [stephenyeargin/hubot-grafana#114]
**Describe the bug**
Command `graf pause all alerts` and `graf unpause all alerts` does not work. Bot returns a permission denied error when trying in Slack. This is because the endpoint `admin/pause-all-alerts` is part of [Grafana Admin API](https://grafana.com/docs/http_api/admin/#pause-all-alerts) and it is clearly mentioned in Grafana documentation that _The Admin HTTP API does not currently work with an API Token._

**To Reproduce**
1. Data source '...'
2. Command entered `myhubot graf unpause all alerts`
3. In slack it says permission denied. In Grafana logs its logged that grafana responded with 403.

**Expected behavior**
It should pause all alerts in one go.

**Software:**
 - Grafana: v6.2.4
 - Hubot: latest
 - Adapter: Slack, or Any
 - Node: <version>
 - NPM: <version>

**Comment by stephenyeargin** [comment]
Context: This was introduced in #82 via @kongo2002. 

Perhaps the endpoint restriction was introduced in a later version of Grafana?

**Comment by liptanbiswas** [comment]
@stephenyeargin Submitted a PR which iterates through all alerts of that organization and tries to pause/unpause one by one. Found [this](https://community.grafana.com/t/how-to-specify-organisation-when-pausing-all-alerts/762/3?u=liptan) which says its a feature that Grafana admin api is not accessible using API keys, so I believe it is going to remain like that. Can you please review the PR and share your  thoughts.

**Comment by stephenyeargin** [comment]
Fixed in `v2.3.2`.
