### ISSUE TITLE
Bar Guage not rendered correctly

### ISSUE THREAD

**Issue by spacertechie** [stephenyeargin/hubot-grafana#120]
**Describe the bug**
When calling a Bar Guage graph in Slack, the text and color bars are badly sized instead of normally being uniform. One stat's number is huge the others are smaller and the colored bar is thinner. Like it just needs another .1s to finish rendering properly.

**To Reproduce**
1. Create a Bar Graph visualization with a few (3-6) stats in it. 
2. Use any "style" it's messed up in different ways for different styles.
3. In slack, call @hubot_grafana graf db:my_bar_guage

**Expected behavior**
The bar guage is normally rendered as it appears in grafana - the text and colored bars of the stats present are all uniform.

**Screenshots**
pending

**Software:**
 - Grafana: v6.3.X
 - Hubot: v3.3.2
 - Adapter: Slack

**Additional context**

**Comment by stephenyeargin** [comment]
Thanks for reporting. Do you have a screenshot? The "rendering" function is handled completely within your Grafana instance itself, so some of the flaws may be an upstream issue. One thing to check is click on a panel, select **Share > Direct link rendered Image** to ensure that it is appearing there as expected. That said, there may be some defaults that need to be changed to work with your particular use case.

![Screen Shot 2019-11-27 at 2 01 57 PM](https://user-images.githubusercontent.com/80459/69755735-84078d80-111e-11ea-8c25-6d5bb79481c6.png)

**Comment by spacertechie** [comment]
Hi! Thanks so much for getting back to us! I think we'll opt out of the bar guage for now actually. We are having another issue though - when multiple graphs are called, only two are rendered and the others are a blank message. Opening a new issue for that though thanks again!
