### ISSUE TITLE
integrating with flowdock

### ISSUE THREAD

**Issue by mitesh1103** [stephenyeargin/hubot-grafana#122]
Could you please update the grafana.coffee script to integrate with flowdock as well...

**Comment by stephenyeargin** [comment]
Interesting idea! I don't use that platform, but can review a PR that integrates with it. It appears there is a [Flowdock Hubot adapter](https://github.com/flowdock/hubot-flowdock), so it should respond with the default text links. Not as shiny as the Slack/Rocketchat integration, but useful.

It also may be time to refactor those individual code paths out of that gigantic switch statement based on the adapter type.
