### ISSUE TITLE
TimeZone support

### ISSUE THREAD

**Issue by KeesCBakker** [stephenyeargin/hubot-grafana#130]
**Is your feature request related to a problem? Please describe.**
Grafana supports time-zones. Let's expose it as well. This might fix some of my dashboards.

**Describe the solution you'd like**
I'll add time-zone support to the `imageUrl`. It can be explicitly added as `tz=`, just like `width=`. Or it can be set globally with the env var `HUBOT_GRAFANA_DEFAULT_TIME_ZONE`.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Notes**
I'll send a pull request with the feature.

**Comment by KeesCBakker** [comment]
Any luck in deploying it to NPM?

**Comment by stephenyeargin** [comment]
Thank you for the reminder. Released as part of `v2.4.0`.
