### ISSUE TITLE
Grafana 7: Full screen leads to localhost:3000 redirect

### ISSUE THREAD

**Issue by KeesCBakker** [stephenyeargin/hubot-grafana#132]
**Describe the bug**
When a dashboard is rendered, a link to the "fullscreen" dashboard is generated as well. This link looks like this:

```https://my.dashboards.link/dashboard/db/team-tooling/?panelId=1&fullscreen&from=now-6h&to=now```

But when I click it, it redirects to:

```http://localhost:3000/d/lHzvLGpGk/team-tooling?from=now-6h&to=now&viewPanel=1```

But when I change the link to this, it works:

```https://my.dashboards.link/dashboard/db/team-tooling/?panelId=1&viewPanel=1&from=now-6h&to=now```

Here I removed the `fullscreen` parameter. I added a `viewPanel=` parameter.

We're running **Grafana v7.1.3 (5723d951af)**

**To Reproduce**
1. Grafana 7
1. Request panel through bot
1. Click on link in the Slack message

**Expected behavior**
I would expect the link to work. By changing the link it works.

**Screenshots**
N/A

**Work-a-round**
I've patched the `msg.send` method to intercept the message to Slack and changed the message:
```js
            let item = payload.attachments[0];

            item.fallback = item.fallback.replace("&fullscreen", "");
            item.title_link = item.title_link.replace("&fullscreen", "");

            item.fallback = item.fallback.replace(/panelId=(\d+)/, "panelId=$1&viewPanel=$1");
            item.title_link = item.title_link.replace(/panelId=(\d+)/, "panelId=$1&viewPanel=$1");
```

**Software:**
 - Grafana: Grafana v7.1.3 (5723d951af)
 - Hubot: 3.3.2
 - Adapter: Slack
 - Node: v12.19.0
 - NPM: 6.14.8

**Additional context**
N/A

**Comment by KeesCBakker** [comment]
I'm happy to create a PR that changes the link into a view-panel instead of the `fullscreen` based on a config value.

**Comment by stephenyeargin** [comment]
A little weird that Grafana would redirect back to an absolute link (including port) rather than a relative link, and even weirder that the `fullscreen` parameter changes this behavior. Can change the behavior regardless, but is there a chance this is a bug in Grafana?

**Comment by KeesCBakker** [comment]
I'm almost sure it has something to do with Grafana, at the office we're looking into it as well.

**Comment by stephenyeargin** [comment]
Closing this out for now. Can re-open if needed.
