### ISSUE TITLE
Can only receive 1 image by each query which queries all panels in the dashboard

### ISSUE THREAD

**Issue by yohey03518** [stephenyeargin/hubot-grafana#141]
**Describe the bug**
<A clear and concise description of what the bug is.>
Before 2.5.2, when there are more than one panel in dashboard and query by below message, I can get multiple images.
`hubot graf db <dashboard-name>`
But in version 3+, I can only get exactly 1 image.
`hubot graf db <dashboard-uid>`

**To Reproduce**
1. Prepare a dashboard with multiple panels
2. `hubot graf db <dashboard-uid>`
3. Can only get 1 message in my channel

**Expected behavior**
Should receive all the images from the dashboard.

**Software:**
 - Grafana: 8.3.4
 - Hubot-Grafana: 3.0.1
 - Hubot: 3.3.2
 - Adapter: Slack

**Additional context**
I have noticed that in [this version](https://github.com/stephenyeargin/hubot-grafana/commit/02dae4eece2fae6da0b949619d4019cc0734d88f#diff-6115ba282c0521627af1a33f2c88df3f926b427711b33d0128a7d0252dc82daeR248), there is a `return` for `robot.respond` .
Also [a corresponding unit test](https://github.com/stephenyeargin/hubot-grafana/commit/a7a4a1bd359a9a2664ead6ddb7bee86a060358be#diff-261533a052c50fe60172f0aede2e9367c949530f14b86e33d81efec64ecddc1f) on the next commit.
It seem you did want to return only first panel. 
I am not sure the reason for adding this (maybe due to performance?), but I am thinking about whether this can be controlled by a configuration? 
For example maybe can use `HUBOT_GRAFANA_MAX_RETURNED_DASHBOARDS`, to make the number of returned dashboard can be controlled.
And user can query multiple panels with only 1 query.

Look forward to your response. And thanks for the powerful tool :)

**Comment by stephenyeargin** [comment]
Yep, that does appear to be a regression. Working on a fix.

**Comment by yohey03518** [comment]
Hi @stephenyeargin it works now with version `3.1.0` .
Thanks for your help. Have a nice day :)
