### ISSUE TITLE
Allow the bot to respond in a thread

### ISSUE THREAD

**Issue by gkaskonas** [stephenyeargin/hubot-grafana#145]
**Is your feature request related to a problem? Please describe.**
At the moment all panels in a dashboard are returned in separate messages.

**Describe the solution you'd like**
Instead of creating a new message in a room, create a new thread and post the messages there

**Comment by stephenyeargin** [comment]
Looks like something that could be possible.

https://slack.dev/hubot-slack/basic_usage#working-with-threads

I would say that the current behavior should be the default, and (yet another) configuration option would be to push responses as in-thread replies.

**Comment by stephenyeargin** [comment]
Give #146 a spin.

```
npm i --save https://github.com/stephenyeargin/hubot-grafana#slack-threads
```
