### ISSUE TITLE
S3 Region breaks existing setup

### ISSUE THREAD

**Issue by KeesCBakker** [stephenyeargin/hubot-grafana#154]
**Describe the bug**
Looks like the S3 region breaks existing image.

Older version (3.2.2) returns URLs like this: https://snap.s3.amazonaws.com/graph/e0fae61eaba8bbb0494e7d45066f02801d3a3b84.png
The latest version (4.0.0) return URLs like this: https://snap.eu-west-1.s3.amazonaws.com/graph/e0fae61eaba8bbb0494e7d45066f02801d3a3b84.png

Looks like my existing bucket does not support the `eu-west-1` part. Now if I remove that part, the file shows.

Think it is related to this region:
![image](https://github.com/stephenyeargin/hubot-grafana/assets/583193/cb549721-1c29-47d2-9e0d-68743e63d436)

**To Reproduce**
N/A

**Expected behavior**
I expect the existing code to work. But I'm happy to upgrade something else.

**Screenshots**
This this code is the problem:
![image](https://github.com/stephenyeargin/hubot-grafana/assets/583193/cb549721-1c29-47d2-9e0d-68743e63d436)

**Software:**
 - Grafana: n/a
 - Hubot: 7.0
 - Adapter: Slack
 - Node: v18.16.0
 - NPM: 9.4.0

**Additional context**
N/A

**Comment by stephenyeargin** [comment]
Fixed with #155
