### ISSUE TITLE
Refactor platform specific actions to adapters?

### ISSUE THREAD

**Issue by KeesCBakker** [stephenyeargin/hubot-grafana#165]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but it might make maintenance a easier.

We make some choices based on the adapter:

- upload type: https://github.com/stephenyeargin/hubot-grafana/blob/main/src/grafana.js#L76-L85
- response format: https://github.com/stephenyeargin/hubot-grafana/blob/main/src/grafana.js#L473-L514
- actual upload: https://github.com/stephenyeargin/hubot-grafana/blob/main/src/grafana.js#L559-L702

So what if we would refactor this into some sort of an adapter? The adapter could:

- upload the file
- write a response based on what the platform can

Our script just initializes the right adapter (based on the `robot.adapterName`) and uses its methods. The implementations are neatly separated into their own classes.

**Describe the solution you'd like**
Some separation of concerns.

**Describe alternatives you've considered**
N/A

**Additional context**
Would love to work on something like that.

**Comment by KeesCBakker** [comment]
@stephenyeargin, if you have some time, I might have something you can take a look at: https://github.com/KeesCBakker/hubot-grafana/pull/2

**Comment by stephenyeargin** [comment]
Looks like it takes care of the tagged issues, thank you! You should have write access now to this repository if you'd rather create branches there (so that the test suite runs against PRs).

**Comment by KeesCBakker** [comment]
Yeah, upon testing I found some problems. Looks like the S3 route works, but the other routes can never work.

The `grafanaDashboardRequest()`  on https://github.com/stephenyeargin/hubot-grafana/blob/main/src/grafana.js#L611 can never work, as it will not return a URL but is a callback, as is defined here: https://github.com/stephenyeargin/hubot-grafana/blob/main/src/grafana.js#L726-L735

Trying to fix that as well, but Slack won't led me upload files.

Other broken cases:

- RocketChat, per: https://github.com/stephenyeargin/hubot-grafana/blob/main/src/grafana.js#L673
- Telegram, per https://github.com/stephenyeargin/hubot-grafana/blob/main/src/grafana.js#L700

The tests currently are not catching that those uploadTo things are broken. Do you manually test them?
