### ISSUE TITLE
[Windows] Unable to run `npm test`

### ISSUE THREAD

**Issue by stephenyeargin** [stephenyeargin/hubot-grafana#175]
**Describe the bug**

Windows users would like to be able to develop `hubot-grafana` as well. Recent changes in #171 broke the ability to run tests without configuration changes.

**To Reproduce**
1. Use Windows
2. Run `npm run test` in the command line
3. See error

**Expected behavior**
Tests (and other scripts) should run agnostic of the platform.

**Screenshots**

![image](https://github.com/stephenyeargin/hubot-grafana/assets/80459/921b278c-3424-4d8e-91d4-2d4bfcaf8cf7)

**Software:**
 - Grafana: Any
 - Hubot: Any
 - Adapter: Any
 - Node: Any
 - NPM: Any

**Additional context**

First reported in comment on #171.

**Comment by KeesCBakker** [comment]
I'm currently working on https://github.com/stephenyeargin/hubot-grafana/tree/feature/small-refactorings where I fixed it using a dev container. This will keep the local setup clean, while providing a springboard for people that want to help development. Would that work?

**Comment by KeesCBakker** [comment]
Details here: https://github.com/stephenyeargin/hubot-grafana/tree/feature/small-refactorings/.devcontainer

**Comment by stephenyeargin** [comment]
That seems reasonable to me. 👍

**Comment by KeesCBakker** [comment]
Solved by #180
