### ISSUE TITLE
Current Template Overriding Specified Template Value

### ISSUE THREAD

**Issue by lanyonm** [stephenyeargin/hubot-grafana#28]
Hi. I have a dashboard `monitoring-default`, with a single variable, `$server`. When asking hubot-grafana for a specific server's load, I use the following command: `graf db monitoring-default:load server=www-03.example.com now-1h`.

My expectation is that Hubot's response would begin with "www-03.example.com load: ", but instead a different (but valid) variable value is shown. This happens to be the same variable value that loads by default when the `monitoring-default` dashboard is loaded in a browser (the `current` value in the dashboard json).

I am unsure of the nuances and more general use-cases for templates with hubot-grafana, but have successfully been able to achieve the desired result here: https://github.com/criticalmass/hubot-grafana/commit/dfb408492449a17ce14f9234a8886815bdd504d7. If you find this approach acceptable, I can create a PR with the changes.

Cheers!

**Comment by stephenyeargin** [comment]
Hm. I recall roughing in the basic support for having the template variables (#4) and some more recent trouble with it (#19). I don't think I fully understand what `current` means in that context. I believe @Tenzer makes heavy use of templated dashboards, but your branch looks sane. I would say go ahead with the PR.

**Comment by Tenzer** [comment]
The current implementation of setting variables for the dashboards work fine for me. What is the different in URLs between the original and your implementation, when you look at the graph URL Hubot posts?

**Comment by lanyonm** [comment]
Setting variables and the graph returned by hubot are correct - the issue seems to be the data being fed to `formatTitleWithTemplate`, which causes the beginning of the response message to be incorrect.

I'll submit a PR once I can acquaint myself with the tests.

**Comment by stephenyeargin** [comment]
Fixed in `v1.4.6`
