### ISSUE TITLE
Allow users to alias dashboard panels / timeframes

### ISSUE THREAD

**Issue by stephenyeargin** [stephenyeargin/hubot-grafana#3]
Using the default `robot.brain` (often backed by Redis or some other storage), allow the user to alias complex queries. The alias would recall the stored data and replay it as if the user had entered it themselves.

```
hubot grafana alias logins = dashboard webapp-overview:3 now-1h now
hubot grafana alias logins
hubot grafana alias list
```

Mentioned in https://github.com/grafana/grafana/issues/2206#issuecomment-114522344, /cc @torkelo

**Comment by Tenzer** [comment]
Perhaps [hubot-alias](https://www.npmjs.com/package/hubot-alias) could be used instead, it's a more general solution.

**Comment by stephenyeargin** [comment]
@Tenzer Have you had acceptable results with it in practice?

**Comment by Tenzer** [comment]
I never really got around to test it, I guess I haven't really had the need to show the same graph/dashboard enough times to justify me looking into it.

**Comment by stephenyeargin** [comment]
Cool. I will close this off for now and recommend anyone with a need try `hubot-alias` as a workaround. Baking it in here wouldn't be terribly difficult, but it would make the plugin that much more code to maintain.
