### ISSUE TITLE
Switch to native S3 library to use IAM for permissions

### ISSUE THREAD

**Issue by warhammerkid** [stephenyeargin/hubot-grafana#37]
It looks like the library you're using to interact with S3, knox, is not maintained, and is therefore missing common functionality like IAM role support. If you switched to using the AWS SDK, you would be able to get that functionality without any additional effort.

**Comment by stephenyeargin** [comment]
Hmm. Not sure how all that's configured @raventools, but we haven't had any trouble issuing a credential for the bot.

**Comment by stephenyeargin** [comment]
For reference, this is discussed here as well on the `knox` repository: https://github.com/Automattic/knox/issues/262 . You're probably right about it not being actively maintained.

There are apparently a fair number of pros/cons to using the native AWS node package. The biggest concern I have is for folks who have implemented S3-like services, such as [Pithos](https://github.com/exoscale/pithos), would no longer be able to use the package. (#35)

It doesn't look terribly difficult to accomplish, but it will need some more research.

**Comment by warhammerkid** [comment]
I have not worked with any of the S3-like services, but so long as they're truly compatible, you should be able to use the `endpoint` option for the S3 constructor (http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property) to point to your own server.
