### ISSUE TITLE
404 response code

### ISSUE THREAD

**Issue by panda87** [stephenyeargin/hubot-grafana#44]
Hi

Im trying to implement the hubot-grafana in my hubot-slack but I'm getting only 404 response codes.
My hubot-slack \ grafana is on docker container which is just for FYI.

When I use the `hubot graf list` command, I'm getting my dashboard list, but when I'm trying to retrieve a certain dashboard im getting the error below from the hubot logs, 

``` bash
2016/01/30 23:58:31 [I] PhantomRenderer::renderToPng url https:///yy.xx.co/dashboard-solo/db/home?panelId=3&width=1000&height=500&from=now-6h&to=now
2016/01/30 23:58:46 [I] Completed EXT_IP - "GET /render/dashboard-solo/db/home/ HTTP/1.1" 404 Not Found 19 bytes in 15141680us
```

The link in the Slack is the right link but, PNG file in the S3 is the 404 error code.

My Grafana version is 2.6.0 and also hubot npm version is the latest.

Does anyone knows what can be the problem here?

D.

**Comment by stephenyeargin** [comment]
I'm not sure what could be happening, but that step could be an internal issue to Grafana. This package relies on the Grafana's PhantomJS instance to return a PNG. That does not appear to be working well on your docker container. Are you able to generate a PNG file through the web interface?

**Comment by stephenyeargin** [comment]
Closing this one off, as I suspect it's an issue with Grafana's image render function itself.
