### ISSUE TITLE
ECONNREFUSED with API key.

### ISSUE THREAD

**Issue by michaelcoyote** [stephenyeargin/hubot-grafana#45]
I'm using a Grafana API key and I am unable to connect to the instance.  I keep erroring out with the following:

```
hubot> hubot graf list
hubot> [Sun Feb 07 2016 06:54:26 GMT+0000 (UTC)] DEBUG Message 'hubot graf list' matched regex //^\s*[@]?hubot[:,]?\s*(?:(?:grafana|graph|graf) list\s?(.+)?)/i/; listener.options = { id: null }
[Sun Feb 07 2016 06:54:26 GMT+0000 (UTC)] DEBUG Executing listener callback for Message 'hubot graf list'
[Sun Feb 07 2016 06:54:26 GMT+0000 (UTC)] ERROR { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
[Sun Feb 07 2016 06:54:26 GMT+0000 (UTC)] DEBUG false
[Sun Feb 07 2016 06:54:26 GMT+0000 (UTC)] DEBUG false
```

I've tested the API key using `curl` and it works fine.

I did add some `console.log` statements to inspect variables and I noticed that the `authHeader` has some odd formatting around the Authorization:
```
{ Accept: 'application/json',
  Authorization: 'Bearer eyJrIjoiWXXX...XXX0=' }
``` 
I noticed that the "Bearer" statement and the key are surrounded by single quotes.  That seems a bit unusual, but I may be missing something.

Thanks in advance.

**Comment by stephenyeargin** [comment]
>I did add some console.log statements to inspect variables and I noticed that the authHeader has some odd formatting around the Authorization:

So [this](https://github.com/github/hubot/blob/master/src/robot.coffee#L622-L623) indicates that is the correct format, but perhaps something else is at play.

Is your Hubot running on Heroku by chance? `ECONNREFUSED` would indicate to me that something network related is happening. This [StackOverflow comment](http://stackoverflow.com/a/21964460/772387) on a similar issue points to a similar issue in another node application.

**Comment by michaelcoyote** [comment]
Sorry, no Heroku.  Just a shell on a Debian box in our internal datacenter.  

I can do curl to that same instance from the same shell and get a response every time using the `Authorization: Bearer eyJrIjoiWXXX...XXX0=` string as my header however if I switch to `Authorization: 'Bearer eyJrIjoiWXXX...XXX0='` it fails.

Setting `NODE_ENV=production` in my startup script did nothing.

**Comment by michaelcoyote** [comment]
According to the [Grafana API Documentation](http://docs.grafana.org/reference/http_api/) the header is used like this:

```
GET http://your.grafana.com/api/dashboards/db/mydash HTTP/1.1
Accept: application/json
Authorization: Bearer eyJrIjoiT0tTcG1pUlY2RnVKZTFVaDFsNFZXdE9ZWmNrMkZYbk
```
Additionally the example in [RFC 6750](https://tools.ietf.org/html/rfc6750#section-2.1) also leaves out the single quotes:
```
GET /resource HTTP/1.1
Host: server.example.com
Authorization: Bearer mF_9.B5f-4.1JqM
```

**Comment by stephenyeargin** [comment]
Ok, so this starts to look like the culprit. The trouble is that I am using how Hubot's scripting guidelines say to add headers, but the output is invalid. Wonder if something changed upstream? It appears to be limited to certain versions of Grafana and Hubot core.

**Comment by michaelcoyote** [comment]
I'll get the version of Grafana we're working on today and report it here.  I also did a bit more looking around and it seems like other programs construct their headers this way, so I'm not exactly sure *why* it should be an issue here.

**Comment by stephenyeargin** [comment]
Worth noting that what you `console.log`'d may have been [correct per the spec](https://nodejs.org/api/http.html#http_http_get_options_callback) for the `HttpClient` node object as well (which is what `robot.http` provides a wrapper). The assembly of the header string happens further down (and should happen without the quotes).

Wondering if we pointed the script at something like Runscope or a local machine with verbose logging if we could see what headers `actually` make it to the Grafana server.

**Comment by michaelcoyote** [comment]
I think you are right WRT `robot.http` doing the right thing with the header.  I'm afraid I didn't dig into that. 

Instead I did a bit of digging around our infrastructure and got it figured out.  Looks like the folks who set this up used nginx on port 80 and then grafana on another port.  Curl works on both ports but hubot-grafana didn't in my case. The fix was to aim directly at the grafana port.  My theory is that there is some odd interop between `robot.http` and nginx/grafana enough to foul the key passing.

Again, thanks for your help.  I'm going to close this, however if we want to dig into this further, please feel free to reopen.
