### ISSUE TITLE
Unable to upload to S3

### ISSUE THREAD

**Issue by nhannguyen** [stephenyeargin/hubot-grafana#49]
Hi,
I'm trying to make hubot-grafana to upload graphs to S3, but I only get these errors

```
[Mon Jun 27 2016 18:31:09 GMT+0700 (ICT)] ERROR Upload Error Code: 307
[Mon Jun 27 2016 18:31:09 GMT+0700 (ICT)] ERROR Upload Error Code: 307
[Mon Jun 27 2016 18:31:10 GMT+0700 (ICT)] ERROR Upload Error Code: 307
[Mon Jun 27 2016 18:31:10 GMT+0700 (ICT)] ERROR Upload Error Code: 307
```

Here's my config

```
export HUBOT_GRAFANA_HOST=https://my-grafana.com
export HUBOT_GRAFANA_API_KEY=MY-API-KEY
export HUBOT_GRAFANA_S3_BUCKET=grafana-graphs
export HUBOT_GRAFANA_S3_ACCESS_KEY_ID=MY-ACCESS-KEY-ID
export HUBOT_GRAFANA_S3_SECRET_ACCESS_KEY=MY-SECRET-ACCESS-KEY
export HUBOT_GRAFANA_S3_REGION=ap-southeast-1
```

When I tested the credential with awscli, it worked.
Did I do anything wrong or miss anything?

**Comment by stephenyeargin** [comment]
So, doing a bit of research on Error Code 307 indicates that perhaps the bucket is not in the S3 Region you have specified?

Ref: http://serverfault.com/questions/730958/error-response-was-307-temporary-redirect-when-trying-to-upload-to-buck
