### ISSUE TITLE
PNG of login screen only

### ISSUE THREAD

**Issue by ericescalante** [stephenyeargin/hubot-grafana#50]
Hi! We are having a  curious issue. When issuing a command, the hubot script connects correctly to grafana and calls the correct dashboard, as can be seen via `HUBOT_LOG_LEVEL=debug`:

```
title: 'Coresites Performance',
  tooltip: { shared: true, value_type: 'cumulative' },
  type: 'graph',
```

But the screenshot we get uploaded is only of the Grafana login screen for some reason. Any ideas?

**Comment by stephenyeargin** [comment]
This may be something odd with the way PhantomJS is running in your instance of Grafana. Couple things to check:

- version of Grafana (I'll admit I haven't tested it with all of them)
- does the PNG render out of the native UI without issue?
- anything special about your network (VPC, etc.) that may affect HTTP traffic?

**Comment by ericescalante** [comment]
Hi Stephen, thanks for replying. It's the latest Grafana (3.1) on a docker container in an EC2 instance. Just browsing on their repo found this bug:

https://github.com/grafana/grafana/issues/4506

I'll close this ticket, since node doesn't look like the culprit! :)
