### ISSUE TITLE
hubot grafana ssl issue

### ISSUE THREAD

**Issue by flakeman2** [stephenyeargin/hubot-grafana#51]
Getting this error after installing the module:

[Tue Nov 01 2016 15:21:05 GMT-0700 (PDT)] ERROR { Error: unable to verify the first certificate
  at Error (native)
  at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
  at emitNone (events.js:86:13)
  at TLSSocket.emit (events.js:185:7)
  at TLSSocket._finishInit (_tls_wrap.js:584:8)
  at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
 code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }

Any ideas?

**Comment by stephenyeargin** [comment]
It appears something is going awry in downloading the node dependencies. Your version of node appears to be unable to verify the certificate chain of the remote package source. A cursory search suggests a few routes:

- Try again later (something may be wrong at NPM)
- Set a global configuration option:
```
npm config set strict-ssl false
```
- Set the `NODE_TLS_REJECT_UNAUTHORIZED` to `0`
```
export NODE_TLS_REJECT_UNAUTHORIZED=0
```

If this is happening _after_ the bot has already started (for example, when attempting to communicate with your Grafana instance), the trouble may be with the way the certificate is set up there. You can debug a mis-configured trust chain with:

```
openssl s_client -connect your-grafana-host.example.com:443
```

Let me know if this helps.
