### ISSUE TITLE
Rendered images does not show all legends

### ISSUE THREAD

**Issue by DonEmil** [stephenyeargin/hubot-grafana#52]
It seems that when I get some images returned the legends are not all displayed.

I've tested with different resolutions, including fullscreen.

![legends](https://cloud.githubusercontent.com/assets/21952460/20566251/b101a664-b194-11e6-9208-67718154b68c.png)

**Comment by stephenyeargin** [comment]
This appears to be an issue with the PNG rendering engine within Grafana rather than what the plugin in requesting. That said, there may be some options we should be sending along to allow for more space in rendering.

/cc @torkelo

**Comment by stephenyeargin** [comment]
You may be able to resolve this with bumping up the height of the rendered graph (introduced with #57). Otherwise, it is something that will need to be resolved with Grafana itself.
