### ISSUE TITLE
Missing Legends

### ISSUE THREAD

**Issue by rohitrsh** [stephenyeargin/hubot-grafana#55]
Hi Team,

First of thanks for that great tool.

We have integrated grafana with hubot to fetch graphs on slack, but with all graphs we have noticed strange behavior that we are not able see legends in reverend image.
Attaching image below
![image](https://cloud.githubusercontent.com/assets/17526588/23713151/f83468ce-044a-11e7-9a80-18e7ade224c3.png)

Kindly help me to know what i am missing here.

-Rohit

**Comment by stephenyeargin** [comment]
Glad you're enjoying the package! So, to debug things, can you confirm that going to that particular graph in Grafana and selecting `Share > Direct link rendered image` displays the legend? There's been some oddness with legends (see also #52).

<img width="132" alt="share" src="https://cloud.githubusercontent.com/assets/80459/23713769/910720be-03ec-11e7-9a82-2c5a7f3f8643.png">

<img width="694" alt="rendered-image" src="https://cloud.githubusercontent.com/assets/80459/23713770/910a2be2-03ec-11e7-81fb-e631201fde40.png">


/cc @torkelo

**Comment by rohitrsh** [comment]
Hi Stephen,

I have tried to debug it, while clicking on `Direct link rendered image` I am getting same output as above.

Attaching snapshot below
![image](https://cloud.githubusercontent.com/assets/17526588/23736736/097dedee-04b4-11e7-83c8-44514c2be8d0.png)

-Rohit

**Comment by stephenyeargin** [comment]
Ok, so that means the bug is in Grafana itself, and not in this Hubot package. This script package is designed to retrieve the same image that the server would generate.

The next step is to [file a bug with Grafana](https://github.com/grafana/grafana/issues/new). You can link back to this issue as a use-case.

**Comment by rohitrsh** [comment]
Thanks Stephen, for prompt response. 

Will raise it with grafana team.

-Rohit

**Comment by rohitrsh** [comment]
Hello Stephen,

I have raised it on Grafana gitub repo, also i have included you in the issue for further updates.

-Rohit

**Comment by torkelo** [comment]
please don't its just that your sever is missing fontlibs packages. ah, will update the issue you posted
