### ISSUE TITLE
Support for Grafana 5.0

### ISSUE THREAD

**Issue by mfilotto** [stephenyeargin/hubot-grafana#66]
Hello,
I try to use grafana hubot script with no luck

**My Grafana version is 5.0**
**Hubot-gafana 1.8.0**

Here are the problems I noticed so far:
- [x]  following error when trying to display a db : `Cannot read property 'length' of undefined`
- [x]  `graf list` return dbs and folders, if I try to display a folder I get an error `Cannot read property 'list' of undefined`
- [ ]  Search by slug is deprecated and will be removed, search by uid should be used instead

I get these error

> Mar 08 13:16:51 dbk-apldev-01v docker[10406]: [Thu Mar 08 2018 02:16:51 GMT+0000 (UTC)] DEBUG Executing listener callback for Message 'hubot graf db dotann-prod'
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: [Thu Mar 08 2018 02:16:51 GMT+0000 (UTC)] DEBUG [ 'hubot graf db dotann-prod',
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: 'dotann-prod',
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: undefined,
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: index: 0,
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: input: 'hubot graf db dotann-prod' ]
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: [Thu Mar 08 2018 02:16:51 GMT+0000 (UTC)] DEBUG dotann-prod
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: [Thu Mar 08 2018 02:16:51 GMT+0000 (UTC)] DEBUG { from: 'now-6h', to: 'now' }
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: [Thu Mar 08 2018 02:16:51 GMT+0000 (UTC)] DEBUG
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: [Thu Mar 08 2018 02:16:51 GMT+0000 (UTC)] DEBUG []
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: [Thu Mar 08 2018 02:16:51 GMT+0000 (UTC)] DEBUG false
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: [Thu Mar 08 2018 02:16:51 GMT+0000 (UTC)] DEBUG false
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: [Thu Mar 08 2018 02:16:51 GMT+0000 (UTC)] DEBUG false
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: [Thu Mar 08 2018 02:16:51 GMT+0000 (UTC)] DEBUG { meta:
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: { type: 'db',
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: canSave: true,
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: canEdit: true,
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: canAdmin: false,
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: canStar: true,
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: slug: 'dotann-prod',
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: url: '/d/-RR2kFekk/dotann-prod',
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: expires: '0001-01-01T00:00:00Z',
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: created: '0001-01-01T11:05:48+11:05',
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: updated: '2018-03-07T09:15:44+11:00',
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: updatedBy: 'admin',
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: createdBy: 'admin',
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: version: 9,
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: hasAcl: false,
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: isFolder: false,
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: folderId: 9,
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: folderTitle: 'NEED',
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: folderUrl: '/dashboards/f/T9wR7L6kz/need' },
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: dashboard:
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: { annotations: { list: [Object] },
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: editable: true,
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: gnetId: null,
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: graphTooltip: 0,
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: id: 3,
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: links: [],
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: panels: [ [Object], [Object] ],
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: refresh: '5m',
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: schemaVersion: 16,
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: style: 'dark',
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: tags: [],
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: templating: { list: [] },
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: time: { from: 'now-6h', to: 'now' },
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: timepicker: { refresh_intervals: [Object], time_options: [Object] },
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: timezone: '',
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: title: 'Dotann PROD',
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: uid: '-RR2kFekk',
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: version: 9 } }
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: [Thu Mar 08 2018 02:16:51 GMT+0000 (UTC)] DEBUG []
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: [Thu Mar 08 2018 02:16:51 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'length' of undefined
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: at /home/hubot/node_modules/hubot-grafana/src/grafana.coffee:167:7
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: at /home/hubot/node_modules/hubot-grafana/src/grafana.coffee:314:14
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: at IncomingMessage.<anonymous> (/home/hubot/node_modules/hubot/node_modules/scoped-http-client/src/index.js:95:22)
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: at emitNone (events.js:72:20)
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: at IncomingMessage.emit (events.js:166:7)
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: at endReadableNT (_stream_readable.js:923:12)
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: at nextTickCallbackWith2Args (node.js:511:9)
Mar 08 13:16:51 dbk-apldev-01v docker[10406]: at process._tickCallback (node.js:425:17)

**Comment by stephenyeargin** [comment]
@mfilotto It looks like there were some breaking changes in v5 we're not ready for. This has happened in previous versions, so I need to better understand what changed.

https://github.com/stephenyeargin/hubot-grafana/blob/fb6d23d3e48c27596478e88f88ab6dc7cd8f99d4/src/grafana.coffee#L141-L150

**Comment by mechko** [comment]
I've got a similar issue, Grafana 5.0.0 as well, hubot-grafana 1.8.0. _graf list_ command is working, _graf db <dashboard>_ not. This is the output when trying to _db graf db foo_:

Error Stacktrace:
`hubot_1  | [Thu Mar 08 2018 13:23:24 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'length' of undefined
hubot_1  |     at /home/hubot/node_modules/hubot-grafana/src/grafana.coffee:167:7
hubot_1  |     at /home/hubot/node_modules/hubot-grafana/src/grafana.coffee:314:14
hubot_1  |     at IncomingMessage.<anonymous> (/home/hubot/node_modules/hubot/node_modules/scoped-http-client/src/index.js:95:22)
hubot_1  |     at emitNone (events.js:72:20)
hubot_1  |     at IncomingMessage.emit (events.js:166:7)
hubot_1  |     at endReadableNT (_stream_readable.js:923:12)
hubot_1  |     at nextTickCallbackWith2Args (node.js:511:9)
hubot_1  |     at process._tickCallback (node.js:425:17)`

Debug output with dashboard object: 

`hubot_1  | [Thu Mar 08 2018 13:23:24 GMT+0000 (UTC)] DEBUG Executing listener callback for Message 'b graf db foo'
hubot_1  | [Thu Mar 08 2018 13:23:24 GMT+0000 (UTC)] DEBUG [ 'b graf db foo',
hubot_1  |   'foo',
hubot_1  |   undefined,
hubot_1  |   index: 0,
hubot_1  |   input: 'b graf db foo' ]
hubot_1  | [Thu Mar 08 2018 13:23:24 GMT+0000 (UTC)] DEBUG foo
hubot_1  | [Thu Mar 08 2018 13:23:24 GMT+0000 (UTC)] DEBUG { from: 'now-6h', to: 'now' }
hubot_1  | [Thu Mar 08 2018 13:23:24 GMT+0000 (UTC)] DEBUG
hubot_1  | [Thu Mar 08 2018 13:23:24 GMT+0000 (UTC)] DEBUG []
hubot_1  | [Thu Mar 08 2018 13:23:24 GMT+0000 (UTC)] DEBUG false
hubot_1  | [Thu Mar 08 2018 13:23:24 GMT+0000 (UTC)] DEBUG false
hubot_1  | [Thu Mar 08 2018 13:23:24 GMT+0000 (UTC)] DEBUG false
hubot_1  | [Thu Mar 08 2018 13:23:24 GMT+0000 (UTC)] DEBUG { meta:
hubot_1  |    { type: 'db',
hubot_1  |      canSave: true,
hubot_1  |      canEdit: true,
hubot_1  |      canAdmin: false,
hubot_1  |      canStar: true,
hubot_1  |      slug: 'foo',
hubot_1  |      url: '/d/CtkEB7gmz/foo',
hubot_1  |      expires: '0001-01-01T00:00:00Z',
hubot_1  |      created: '2018-03-08T13:22:22Z',
hubot_1  |      updated: '2018-03-08T13:22:49Z',
hubot_1  |      updatedBy: 'admin',
hubot_1  |      createdBy: 'admin',
hubot_1  |      version: 3,
hubot_1  |      hasAcl: false,
hubot_1  |      isFolder: false,
hubot_1  |      folderId: 0,
hubot_1  |      folderTitle: 'General',
hubot_1  |      folderUrl: '' },
hubot_1  |   dashboard:
hubot_1  |    { annotations: { list: [Object] },
hubot_1  |      editable: true,
hubot_1  |      gnetId: null,
hubot_1  |      graphTooltip: 0,
hubot_1  |      id: 2,
hubot_1  |      links: [],
hubot_1  |      panels: [ [Object] ],
hubot_1  |      schemaVersion: 16,
hubot_1  |      style: 'dark',
hubot_1  |      tags: [],
hubot_1  |      templating: { list: [] },
hubot_1  |      time: { from: 'now-6h', to: 'now' },
hubot_1  |      timepicker: { refresh_intervals: [Object], time_options: [Object] },
hubot_1  |      timezone: '',
hubot_1  |      title: 'foo',
hubot_1  |      uid: 'CtkEB7gmz',
hubot_1  |      version: 3 } }
hubot_1  | [Thu Mar 08 2018 13:23:24 GMT+0000 (UTC)] DEBUG []`

Fun Fact: The Grafana HTTP API doc has the _rows_ property in all example dashboard objects, also for v5.0: http://docs.grafana.org/http_api/dashboard/#get-dashboard-by-uid (haven't debugged this further, don't what endpoint you're calling.

If you need help for debugging / testing, please let me know.

**Comment by stephenyeargin** [comment]
Looping in @torkelo to see if he has any insight into what might have changed in v5.0.

**Comment by stephenyeargin** [comment]
This change (under [5.0.0-beta1](https://github.com/grafana/grafana/blob/master/CHANGELOG.md#500-beta1-2018-02-05)) may be related:

https://github.com/grafana/grafana/blob/master/CHANGELOG.md#http-api

**Comment by mfilotto** [comment]
Search by slug is deprecated and will be remove, search by uid should be used instead.
http://docs.grafana.org/http_api/dashboard/#deprecated-resources

Another impact : `graf list` displays dbs and folders, so the search should be filtered by type `data-db`
http://docs.grafana.org/http_api/folder_dashboard_search/

**Comment by stephenyeargin** [comment]
So the question will become how to maintain functionality for  both`<= v4` and `v5`.

**Comment by stephenyeargin** [comment]
See #67. If anyone has a moment, I'd love a 👍 after testing.

**Comment by mechko** [comment]
Tested this, works for my Grafana 5 instance. Many thanks 👍

**Comment by stephenyeargin** [comment]
@mfilotto I've knocked out two of the items you've highlighted, but the deprecated bit can be tackled in a new Issue/PR since the current functionality isn't broken per se, but will be in the future. Going to send out a release this morning with #67 in it.

**Comment by stephenyeargin** [comment]
Released with [`v2.0.0`](https://github.com/stephenyeargin/hubot-grafana/releases/tag/v2.0.0).

**Comment by mfilotto** [comment]
It's working just fine :+1: 
Thanks @stephenyeargin
