### ISSUE TITLE
Rocket.chat file upload support

### ISSUE THREAD

**Issue by mfilotto** [stephenyeargin/hubot-grafana#69]
My use case is to use Rocketchat.chat to store png files instead of S3.
This way all my files uploaded in Rocketchat are managed the same way.

I implemented this feature the same way as Slack uploads

**Comment by mfilotto** [comment]
This feature is available in Rocket.chat since 0.62.0
https://rocket.chat/docs/developer-guides/rest-api/rooms/upload/

**Comment by stephenyeargin** [comment]
Closed via #70 , released in `v2.1.0`.
