### ISSUE TITLE
Templated dashboards

### ISSUE THREAD

**Issue by Tenzer** [stephenyeargin/hubot-grafana#7]
We have one dashboard which show general metrics for each server collected with collectd. It is set up as a templated dashboard where we pick the name of the server we want to get the metrics for. Having an ability to specify a value for a templated dashboard would allow us to use this dashboard for all servers and specify that ie. want metrics for the "nginx" server.

I assume it would have to be specified as a key=value pair, since there may be multiple values for a templated dashboard.

**Comment by stephenyeargin** [comment]
Interesting. Do you have any ideas on how you would want to interact with the robot for those?

**Comment by Tenzer** [comment]
I guess being able to add `key=value` somewhere after the dashboard name would work. The parsing of parameters could however become a bit cumbersome.
Perhaps it would be easier to extend if everything following the `slug:pid` is splitted be spaces and then tested against if it contains an equals sign? If not, then the first one is assigned to the `from` variable and the second to `to`?
