### ISSUE TITLE
Fetch entire dashboard instead of panels

### ISSUE THREAD

**Issue by flyingbarron** [stephenyeargin/hubot-grafana#72]
Grafana can render the entire dashboard in one go using : 
http://1.2.3.4:3000/render/d/randompath/myDashboardName

This results in a very nice image that can sometimes be more useful than the specific panels.

**Comment by stephenyeargin** [comment]
Interesting! I'm guessing this is a new feature in Grafana?

Since so many people depend on this package these days, I want to make sure I don't cause any headache in userland. Can you attach some screenshots comparing the two?

**Comment by RobertJBarron** [comment]
here's an example : http://play.grafana.org/render/d/000000061/1-promcon-dashboard?from=now-1h&to=now&orgId=1

![image](https://user-images.githubusercontent.com/7903045/38321332-feee9c3c-383f-11e8-94d5-29524f0048e9.png)

not all dashboards will come out looking better this way - but quite a few will!

**Comment by stephenyeargin** [comment]
Cool. I think this should probably be an opt-in feature, if only because there's a lot of extra stuff in the image (mostly noting the icons) that some folks may not want. Would be something like adding an option for `HUBOT_GRAFANA_RENDER_DASHBOARD=1` (defaults to `0`).

**Comment by RobertJBarron** [comment]
I was actually thinking maybe just add a new command `graf render <dashboard slug>`
That way you have full backwards compatibility

**Comment by KeesCBakker** [comment]
Awesome feature, I just added a `kiosk` feature, so you can do `graf db GZ3rrHgSk kiosk width=1920 height=1200 now now-7d`

![image](https://github.com/stephenyeargin/hubot-grafana/assets/583193/d8170108-8d86-4ca8-86e2-0c4c66715f65)

**Comment by KeesCBakker** [comment]
Added it to https://github.com/stephenyeargin/hubot-grafana/pull/166
