### ISSUE TITLE
Cannot see the image in Slack

### ISSUE THREAD

**Issue by tlytg456** [stephenyeargin/hubot-grafana#84]
Hello, 
I met a problem for my hubot and slack.
After configing the grafana, hubot, S3 correctly, and ask for a certain dashboard, the slack bot only give me a link to the dashboard, without the dashboard screen shot image.

I looked for the S3 buckets, for every link, it indeed store a "png" file, but their content is json like below:

![image](https://user-images.githubusercontent.com/13758960/44515827-1a682a80-a6f6-11e8-928d-a17b37625ee4.png)

I do not know how to act, could anyone help please?

**Software:**
 - Grafana: v5.1.0
 - Hubot: 3.1.1
 - Adapter: Slack
 - Node: 8.9.1
 - NPM: 5.5.1

**Comment by stephenyeargin** [comment]
If you're using the Slack adapter, it will use its own upload functionality *if* S3 isn't configured. For simplicity, I'd recommend removing the S3 portion.

That said, it _should_ be uploading to S3 properly. Do you have any relevant log entries when querying the dashboards?
